color0 #17120f
color1 #ffb4ab
color2 #ffb779
color3 #e3c0a5
color4 #c3cb97
color5 #ffb779
color6 #e3c0a5
color7 #ece0da
color8 #9e8e82
color9 #ffb4ab
color10 #ffb779
color11 #e3c0a5
color12 #c3cb97
color13 #ffb779
color14 #e3c0a5
color15 #ece0da

cursor                #ece0da
cursor_text_color     #17120f
background            #17120f
foreground            #ece0da
selection_foreground  #d6c3b6
selection_background  #51443a
active_border_color   #ffb779
inactive_border_color #51443a
url_color             #ffb779

active_tab_foreground   #4c2700
active_tab_background   #ffb779
inactive_tab_foreground #d6c3b6
inactive_tab_background #51443a
cursor_trail_color      #d6c3b6
